### ISSUE TITLE
This crashed during a drag and drop in sample app: IndexOutOfBoundsException: Index: 6, Size: 5

### ISSUE THREAD

**Issue by eboudrant** [Doist/RecyclerViewExtensions#11]
```
05-03 09:42:40.027  5164  5164 E AndroidRuntime: Process: io.doist.recyclerviewext, PID: 5164
05-03 09:42:40.027  5164  5164 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 6, Size: 5
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:457)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at io.doist.recyclerviewext.demo.DemoAdapter.onSwap(DemoAdapter.java:119)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at io.doist.recyclerviewext.dragdrop.DragDropHelper.handleSwap(DragDropHelper.java:555)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at io.doist.recyclerviewext.dragdrop.DragDropHelper.onDraw(DragDropHelper.java:298)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:3934)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.View.draw(View.java:17185)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16167)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-03 09:42:40.027  5164  5164 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by goncalossilva** [comment]
Hi @eboudrant, thanks for the report!

Can you provide some context as to how you triggered this crash?

**Comment by goncalossilva** [comment]
Closing due to inactivity.
