### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by JakeWoki** [Doist/RecyclerViewExtensions#19]
``` Java
FATAL EXCEPTION: mainProcess: io.doist.recyclerviewext, PID: 28482
java.lang.ArrayIndexOutOfBoundsException: length=6; index=24
    at io.doist.recyclerviewext.animations.AnimatedAdapter$Items.setChangeHash(AnimatedAdapter.java:267)
    at io.doist.recyclerviewext.animations.AnimatedAdapter$LocalStateObserver.onItemRangeChanged(AnimatedAdapter.java:200)
    at android.support.v7.widget.RecyclerView$AdapterDataObserver.onItemRangeChanged(RecyclerView.java:11100)
    at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:11580)
    at android.support.v7.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:6832)
    at io.doist.recyclerviewext.choice_modes.Selector.notifyItemChanged(Selector.java:123)
    at io.doist.recyclerviewext.choice_modes.SingleSelector.setSelected(SingleSelector.java:36)
    at io.doist.recyclerviewext.choice_modes.Selector.toggleSelected(Selector.java:40)
    at io.doist.recyclerviewext.demo.DemoAdapter$DemoItemViewHolder.onClick(DemoAdapter.java:159)
    at android.view.View.performClick(View.java:5646)
    at android.view.View$PerformClick.run(View.java:22459)
    at android.os.Handler.handleCallback(Handler.java:761)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6523)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by goncalossilva** [comment]
Please try the latest master. There have been considerable changes since the bug has been opened. Thanks!
